name: coverage

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:

concurrency:
  group: coverage-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  llvm-cov:
    name: cargo-llvm-cov + codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust
        with:
          components: llvm-tools-preview
          cache-key: coverage
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run cargo llvm-cov
        run: |
          cargo llvm-cov --workspace --locked \
            --lcov --output-path lcov.info
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
